INDIGO_WELCOME_MESSAGE: "Level up your Japanese skills with Showa Boston Institute"
INDIGO_PRIMARY_COLOR: "#3b85ff" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "https://www.showaboston.edu/japanese-program"
  - title: "JLPT at Showa"
    url: "https://www.showaboston.edu/japanese-program/jlpt"
INDIGO_FOOTER_LEGAL_LINKS: []
